# -*- coding: utf-8 -*-
""".gitignore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REMdNWUpwW2aSG7Qrh05G1E03QNS1SxA
"""

# Create a .gitignore file with the correct content
ignore_content = """
# Ignore environment variable files
.env

# Python cache files
__pycache__/
*.pyc
*.pyo
*.pyd

# VSCode settings
.vscode/

# Mac system files
.DS_Store

# Jupyter Notebook checkpoints
.ipynb_checkpoints/

# Render deployment temp files (optional)
*.log
"""

with open(".gitignore", "w") as f:
    f.write(ignore_content)

print(".gitignore file created successfully!")