# -*- coding: utf-8 -*-
"""MainPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkhQbpE0YJ-g0aGAhxqSh0cwdi-27Vor
"""

from fastapi import FastAPI
import requests
import os

app = FastAPI()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")  # FIXED
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"


@app.get("/")
def home():
    return {"status": "running", "service": "AI Summarizer & Sentiment Analyzer"}


def call_openrouter(prompt: str):
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }

    body = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(OPENROUTER_URL, json=body, headers=headers)
    output = response.json()

    print("RAW OPENROUTER RESPONSE:", output)  # DEBUG LINE

    if "choices" not in output:
        return None  # Means error

    return output["choices"][0]["message"]["content"]


@app.post("/summarize")
def summarize(payload: dict):
    text = payload.get("text", "")

    if not text:
        return {"error": "No text provided."}

    prompt = f"""
    Summarize the following text in:
    - 3 Key Bullet Points
    - 1-Sentence TL;DR Summary

    Text:
    {text}
    """

    result = call_openrouter(prompt)

    if not result:
        return {"error": "Could not generate summary."}

    return {"summary": result}


@app.post("/sentiment")
def sentiment(payload: dict):
    text = payload.get("text", "")

    if not text:
        return {"error": "No text provided."}

    prompt = f"""
    Analyze the sentiment of the following text.
    Provide:
    - Sentiment: Positive, Neutral, or Negative
    - Confidence (0–1)
    - One-sentence explanation

    Text:
    {text}
    """

    result = call_openrouter(prompt)

    if not result:
        return {"error": "Could not analyze sentiment."}

    return {"sentiment": result}