# -*- coding: utf-8 -*-
"""Maiiin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPrtYfPtawRjTR_8vSZTg2blvpcvVbty
"""

!pip install fastapi uvicorn nest_asyncio requests

import os
os.environ["OPENROUTER_API_KEY"] = "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"

from fastapi import FastAPI
import requests
import os

app = FastAPI()

# Load API key correctly
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

@app.get("/")
def home():
    return {"status": "running", "service": "AI Summarizer & Sentiment Analyzer"}


@app.post("/summarize")
def summarize(payload: dict):
    text = payload.get("text", "")

    if not text:
        return {"error": "No text provided."}

    prompt = f"""
    Summarize the following text in:

    • 3 Key Bullet Points
    • 1-Sentence TL;DR Summary

    Text:
    {text}
    """

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://your-render-service.com",
        "X-Title": "AI Text Summarizer"
    }

    body = {
        "model": "openai/gpt-4o-mini",   # CORRECT MODEL NAME
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(OPENROUTER_URL, json=body, headers=headers)

    try:
        output = response.json()
        # Extract the summary
        result = output["choices"][0]["message"]["content"]
        return {"summary": result}

    except Exception as e:
        return {
            "summary": None,
            "error": "OpenRouter did not return a valid response.",
            "details": str(e),
            "raw_response": response.text
        }


@app.post("/sentiment")
def sentiment(payload: dict):
    text = payload.get("text", "")

    if not text:
        return {"error": "No text provided."}

    prompt = f"""
    Analyze the sentiment of the following text.
    Provide:

    - Sentiment (Positive, Neutral, or Negative)
    - Confidence (0–1)
    - A one-sentence explanation

    Text:
    {text}
    """

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://your-render-service.com",
        "X-Title": "AI Sentiment Analyzer"
    }

    body = {
        "model": "openai/gpt-4o-mini",
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(OPENROUTER_URL, json=body, headers=headers)

    try:
        output = response.json()
        result = output["choices"][0]["message"]["content"]
        return {"sentiment": result}

    except Exception as e:
        return {
            "sentiment": None,
            "error": "OpenRouter did not return a valid response.",
            "details": str(e),
            "raw_response": response.text
        }
