# -*- coding: utf-8 -*-
"""MainPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkhQbpE0YJ-g0aGAhxqSh0cwdi-27Vor
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI
# import requests
# import os
# 
# app = FastAPI()
# 
# OPENROUTER_API_KEY = os.getenv("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")
# OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
# 
# 
# @app.get("/")
# def home():
#     return {"status": "running", "service": "AI Summarizer & Sentiment Analyzer"}
# 
# 
# @app.post("/summarize")
# def summarize(payload: dict):
#     text = payload.get("text", "")
# 
#     if not text:
#         return {"error": "No text provided."}
# 
#     prompt = f"""
#     Summarize the following text in:
# 
#     - 3 Key Bullet Points
#     - 1-Sentence TL;DR Summary
# 
#     Text:
#     {text}
#     """
# 
#     headers = {
#         "Authorization": f"Bearer {OPENROUTER_API_KEY}",
#         "Content-Type": "application/json",
#         "HTTP-Referer": "https://yourapp.com",
#         "X-Title": "AI Text Summarizer"
#     }
# 
#     body = {
#         "model": "gpt-4o-mini",
#         "messages": [
#             {"role": "user", "content": prompt}
#         ]
#     }
# 
#     response = requests.post(OPENROUTER_URL, json=body, headers=headers)
#     output = response.json()
# 
#     try:
#         result = output["choices"][0]["message"]["content"]
#     except:
#         result = "Error: Could not generate summary."
# 
#     return {"summary": result}
# 
# 
# @app.post("/sentiment")
# def sentiment(payload: dict):
#     text = payload.get("text", "")
# 
#     if not text:
#         return {"error": "No text provided."}
# 
#     prompt = f"""
#     Analyze the sentiment of the following text.
#     Provide:
# 
#     - Sentiment: Positive, Neutral, or Negative
#     - Confidence (0–1)
#     - One-sentence explanation
# 
#     Text:
#     {text}
#     """
# 
#     headers = {
#         "Authorization": f"Bearer {OPENROUTER_API_KEY}",
#         "Content-Type": "application/json",
#         "HTTP-Referer": "https://yourapp.com",
#         "X-Title": "AI Sentiment Analyzer"
#     }
# 
#     body = {
#         "model": "gpt-4o-mini",
#         "messages": [
#             {"role": "user", "content": prompt}
#         ]
#     }
# 
#     response = requests.post(OPENROUTER_URL, json=body, headers=headers)
#     output = response.json()
# 
#     try:
#         result = output["choices"][0]["message"]["content"]
#     except:
#         result = "Error: Could not analyze sentiment."
# 
#     return {"sentiment": result}
#